### ISSUE TITLE
🐛 Weather.py frequently throws stacktrace trying to parse JSON

### ISSUE THREAD

**Issue by trinitronx** [manjaro-sway/manjaro-sway#842]
### branch

unstable

### Architecture

x86_64

### Description

`/usr/share/sway/scripts/weather.py` frequently throws stacktraces when trying to parse the weather JSON API's response.  Can be seen in logs from `waybar.service` SystemD user unit via: `journalctl -xen 10000  --user-unit waybar.service  -f`

### Reproduction steps

1. Boot into Manjaro Sway
2. Open a `foot` terminal (<kbd>Mod4</kbd>+<kbd>Enter</kbd>)
3. Start watching logs: `journalctl -xen 10000  --user-unit waybar.service  -f`
4. Eventually the weather waybar module (`weather.py`) throws a stacktrace.  (If left on long enough, it can happen multiple times when it tries to update)
5. The weather waybar module disappears due to the update error

Also reproducible by manually running the `weather.py` script:

```bash
/usr/share/sway/scripts/weather.py
```

### Screenshots

![swappy-20240906_114735](https://github.com/user-attachments/assets/c1f1ba1e-e548-461b-8f61-50374eb21f50)

### Logs

```bash
Sep 06 11:37:17 saturn waybar.sh[34301]: Traceback (most recent call last):
Sep 06 11:37:17 saturn waybar.sh[34301]:   File "/usr/lib/python3.12/site-packages/requests/models.py", line 974, in json
Sep 06 11:37:17 saturn waybar.sh[34301]:     return complexjson.loads(self.text, **kwargs)
Sep 06 11:37:17 saturn waybar.sh[34301]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 06 11:37:17 saturn waybar.sh[34301]:   File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
Sep 06 11:37:17 saturn waybar.sh[34301]:     return _default_decoder.decode(s)
Sep 06 11:37:17 saturn waybar.sh[34301]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 06 11:37:17 saturn waybar.sh[34301]:   File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
Sep 06 11:37:17 saturn waybar.sh[34301]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Sep 06 11:37:17 saturn waybar.sh[34301]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 06 11:37:17 saturn waybar.sh[34301]:   File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
Sep 06 11:37:17 saturn waybar.sh[34301]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Sep 06 11:37:17 saturn waybar.sh[34301]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sep 06 11:37:17 saturn waybar.sh[34301]: During handling of the above exception, another exception occurred:
Sep 06 11:37:17 saturn waybar.sh[34301]: Traceback (most recent call last):
Sep 06 11:37:17 saturn waybar.sh[34301]:   File "/usr/share/sway/scripts/weather.py", line 80, in <module>
Sep 06 11:37:17 saturn waybar.sh[34301]:     weather = requests.get(f"https://manjaro-sway.download/weather/{city}?temperature_unit={temperature_unit}&wind_speed_unit={wind_speed_unit}", timeout=10, headers=headers).json()
Sep 06 11:37:17 saturn waybar.sh[34301]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 06 11:37:17 saturn waybar.sh[34301]:   File "/usr/lib/python3.12/site-packages/requests/models.py", line 978, in json
Sep 06 11:37:17 saturn waybar.sh[34301]:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
Sep 06 11:37:17 saturn waybar.sh[34301]: requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by trinitronx** [comment]
To dig further into the root cause for this, I made a copy of `weather.py` and printed the URL that [the `f""` string][1] and response evaluated to:

```bash
https://manjaro-sway.download/weather/auto?temperature_unit=celsius&wind_speed_unit=kmh
<Response [500]>
```

Then, trying to `curl` this URL it returned a 500 error:

```bash
curl -v 'https://manjaro-sway.download/weather/auto\?temperature_unit\=celsius\&wind_speed_unit\=kmh' 
* Host manjaro-sway.download:443 was resolved.
* IPv6: 2606:4700:3035::6815:2f73, 2606:4700:3030::ac43:937c
* IPv4: 172.67.147.124, 104.21.47.115
*   Trying [2606:4700:3035::6815:2f73]:443...
* Connected to manjaro-sway.download (2606:4700:3035::6815:2f73) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=manjaro-sway.download
*  start date: Sep  6 12:05:45 2024 GMT
*  expire date: Dec  5 12:05:44 2024 GMT
*  subjectAltName: host "manjaro-sway.download" matched cert's "manjaro-sway.download"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://manjaro-sway.download/weather/auto\?temperature_unit\=celsius\&wind_speed_unit\=kmh
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: manjaro-sway.download]
* [HTTP/2] [1] [:path: /weather/auto\?temperature_unit\=celsius\&wind_speed_unit\=kmh]
* [HTTP/2] [1] [user-agent: curl/8.9.1]
* [HTTP/2] [1] [accept: */*]
> GET /weather/auto\?temperature_unit\=celsius\&wind_speed_unit\=kmh HTTP/2
> Host: manjaro-sway.download
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 500 
< date: Fri, 06 Sep 2024 17:57:26 GMT
< content-length: 0
< cf-placement: remote-FRA
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=XEoD5tyXX%2BFnLZ%2BcyC4L%2BkEj86q3j4nyOqvjpdFRCw3iYuml9nifIlLr5oVb6s%2B0awk0VUyGHpiy1Cg%2BBag4TXpEb2p13RoutYfFL8lucjKlLefcgAjOoEf30t0ndUi221CJ62xcx0DhluSLUrwHJ4dOSC4%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 8bf05765ca1251df-DEN
< alt-svc: h3=":443"; ma=86400
< 
* Connection #0 to host manjaro-sway.download left intact
```

[1]: https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/usr/share/sway/scripts/weather.py#L80

**Comment by trinitronx** [comment]
I checked if there was a config file (`${HOME}/.config/weather.cfg`) on my system, but there was none.  Also, in case it matters, there was no `${HOME}/.config/weather.cfg.example`, which indicates that my system install pre-dates this being added to `/etc/skel/.config/`.

**Comment by boredland** [comment]
I am far from a computer right now, but the logs of the weather API report the following:

> Cannot read properties of undefined (reading 'weather_code')

My guess would be, that we're above the rate limits of open-meteo.com, as weather code is the first thing it tries to parse from their payload. Hard to say without further debugging and appropriate logs.

**Comment by boredland** [comment]
We're not rate limited anymore. Let's see how long that holds up. My guess would be that it won't.

**Comment by trinitronx** [comment]
> My guess would be, that we're above the rate limits of open-meteo.com, as weather code is the first thing it tries to parse from their payload. Hard to say without further debugging and appropriate logs.

Makes sense... I figured since it's a `500` error, someone would need server-side log access to track this down.

> Edit: confirmed rate limiting. Added 15 minutes cache to the queries for weather data, hoping that helps for now. Without a computer, editing things is really hard..
> 
> We're not rate limited anymore. Let's see how long that holds up. My guess would be that it won't.

I just re-tested with the `weather.py` script and `curl`... still getting same stacktrace and 500 error today:


<details><summary>Expand for <code>curl</code> HTTP response log details</summary>
<p>

```code
$ curl -v 'https://manjaro-sway.download/weather/auto?temperature_unit=celsius&wind_speed_unit=kmh'  
* Host manjaro-sway.download:443 was resolved.
* IPv6: 2606:4700:3035::6815:2f73, 2606:4700:3030::ac43:937c
* IPv4: 104.21.47.115, 172.67.147.124
*   Trying [2606:4700:3035::6815:2f73]:443...
* Connected to manjaro-sway.download (2606:4700:3035::6815:2f73) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=manjaro-sway.download
*  start date: Sep  6 12:05:45 2024 GMT
*  expire date: Dec  5 12:05:44 2024 GMT
*  subjectAltName: host "manjaro-sway.download" matched cert's "manjaro-sway.download"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://manjaro-sway.download/weather/auto?temperature_unit=celsius&wind_speed_unit=kmh
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: manjaro-sway.download]
* [HTTP/2] [1] [:path: /weather/auto?temperature_unit=celsius&wind_speed_unit=kmh]
* [HTTP/2] [1] [user-agent: curl/8.9.1]
* [HTTP/2] [1] [accept: */*]
> GET /weather/auto?temperature_unit=celsius&wind_speed_unit=kmh HTTP/2
> Host: manjaro-sway.download
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 500 
< date: Sat, 07 Sep 2024 21:51:16 GMT
< content-length: 0
< cf-placement: remote-FRA
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=AFjUfRi6eILmn2ThDRRAdGUG6eANb9jQpY69OGVhdxFuRSCnO6x%2BMYRp%2BLB%2FADSspJP9%2FAje8THKGGWLS0ZsMhp6ZQg9aimkyr%2Fmtk5z%2B7kndQBCGvGF0ryZ%2FYG51fqt%2ByHdHG1YGXWTMKESEGBOpxC6qyM%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 8bf9eb4ea9041f4a-DEN
< alt-svc: h3=":443"; ma=86400
< 
* Connection #0 to host manjaro-sway.download left intact
```

</p>
</details>

I wonder how many users with Manjaro Sway Edition there are?  Given that we are hitting the request limit... :thinking:

**Comment by boredland** [comment]
For me it returns the correct payload.

![Screenshot_20240908-165342.png](https://github.com/user-attachments/assets/27059cc2-b480-4dd1-b767-e90fad570d6f)

**Comment by trinitronx** [comment]
:thinking: I wonder if in my case the API is causing error for some other reason?  I thought perhaps maybe the `auto` endpoint could be the issue, so I tried using the example defaults.

Trying the URL parameters in the `/etc/skel/.config/weather.cfg.example` is giving me the same results:

<details><summary>Expand for <code>curl</code> HTTP response log details with `weather.cfg.example` defaults</summary>
<p>

```console
$ curl -v 'https://manjaro-sway.download/weather/Frankfurt%20am%20Main?temperature_unit=celsius&wind_speed_unit=kmh'

* Host manjaro-sway.download:443 was resolved.
* IPv6: 2606:4700:3035::6815:2f73, 2606:4700:3030::ac43:937c
* IPv4: 172.67.147.124, 104.21.47.115
*   Trying [2606:4700:3035::6815:2f73]:443...
* Connected to manjaro-sway.download (2606:4700:3035::6815:2f73) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=manjaro-sway.download
*  start date: Sep  6 12:05:45 2024 GMT
*  expire date: Dec  5 12:05:44 2024 GMT
*  subjectAltName: host "manjaro-sway.download" matched cert's "manjaro-sway.download"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://manjaro-sway.download/weather/Frankfurt%20am%20Main?temperature_unit=celsius&wind_speed_unit=kmh
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: manjaro-sway.download]
* [HTTP/2] [1] [:path: /weather/Frankfurt%20am%20Main?temperature_unit=celsius&wind_speed_unit=kmh]
* [HTTP/2] [1] [user-agent: curl/8.9.1]
* [HTTP/2] [1] [accept: */*]
> GET /weather/Frankfurt%20am%20Main?temperature_unit=celsius&wind_speed_unit=kmh HTTP/2
> Host: manjaro-sway.download
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 500 
< date: Sun, 08 Sep 2024 18:41:05 GMT
< content-length: 0
< cf-placement: remote-FRA
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=ekIR5oSSSZEXF3r7c4Pj4VONYZ7kFgZ1xzYZvXuBdaDoh3Z%2BEGfwW8fIrPweWc4wrleyjRtURA3cox%2B%2BNLQkWG13FDoOsisqi7SEd48Azp09NqFP6lHsKmONWm6mdfXnirlJRKp1lyaOEYqujW6A3ovFm9I%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 8c011219ed335346-DEN
< alt-svc: h3=":443"; ma=86400
< 
* Connection #0 to host manjaro-sway.download left intact
```

</p>
</details>

**Comment by boredland** [comment]
When you open `https://manjaro-sway.download/weather/Frankfurt%20am%20Main?temperature_unit=celsius&wind_speed_unit=kmh` in your browser, does cloudflare show more information about the error?

**Comment by trinitronx** [comment]
In Firefox, I'm not seeing much extra info... just similar headers and a 500 error with blank page (See screenshot below).  For what it's worth: Last night I tried the same URL in Google Chrome app on iOS and it did return the expected JSON response.

Here's a screenshot:

![swappy-20240909_102606](https://github.com/user-attachments/assets/f04f583c-67ed-4434-bdc9-c67ce9828aab)

**Comment by boredland** [comment]
Back from the holidays and I think I found the bug: cloudflare by default does not cache json responses. We'll see tomorrow if forcing it to cache them will let us stay below the open-meteo rate limits.

**Comment by boredland** [comment]
Did you see more issue during the recent days?

**Comment by boredland** [comment]
as I see it, we didn't run into issues in multiple days. feel free to come back if this persists for you!

**Comment by vandabbin** [comment]
Hi! Sorry if I shouldn't be opening this again. Just wanted to mention that today I am experiencing this same thing

```
* Host manjaro-sway.download:443 was resolved.
* IPv6: 2606:4700:3030::ac43:937c, 2606:4700:3035::6815:2f73
* IPv4: 104.21.47.115, 172.67.147.124
*   Trying [2606:4700:3030::ac43:937c]:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=manjaro-sway.download
*  start date: Nov  4 12:12:24 2024 GMT
*  expire date: Feb  2 12:12:23 2025 GMT
*  subjectAltName: host "manjaro-sway.download" matched cert's "manjaro-sway.download"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* Connected to manjaro-sway.download (2606:4700:3030::ac43:937c) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://manjaro-sway.download/weather/auto?temperature_unit=fahrenheit&wind_speed_unit=mph
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: manjaro-sway.download]
* [HTTP/2] [1] [:path: /weather/auto?temperature_unit=fahrenheit&wind_speed_unit=mph]
* [HTTP/2] [1] [user-agent: curl/8.11.1]
* [HTTP/2] [1] [accept: */*]
> GET /weather/auto?temperature_unit=fahrenheit&wind_speed_unit=mph HTTP/2
> Host: manjaro-sway.download
> User-Agent: curl/8.11.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 500 
< date: Fri, 20 Dec 2024 13:41:36 GMT
< content-length: 0
< cf-placement: remote-FRA
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=qv743ZCNOAurTlg8Iphw9yTTlKnSP6t9%2Ffh0C7bFS08NDM6FHIAn%2F8pXmTXNUYdNIyr%2BtdekpWHDeVeWYAxTGgR%2B3kEYlSih59a1EXATHO6zL6yW%2B13lXaJ%2BBeKF9hnUzUkmDoWSIp3Klv4f55CtmL7D6lQ%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 8f500d07ffb032b7-SMF
< alt-svc: h3=":443"; ma=86400
< server-timing: cfL4;desc="?proto=TCP&rtt=19984&min_rtt=19065&rtt_var=5795&sent=7&recv=8&lost=0&retrans=0&sent_bytes=3389&recv_bytes=804&delivery_rate=207693&cwnd=253&unsent_bytes=0&cid=26d4d63acb52b7bf&ts=308&x=0"
< 
* Connection #0 to host manjaro-sway.download left intact
```

**Comment by varac** [comment]
I get a HTTP error 500 when trying the URL call which the weather script makes:

```sh
$ curl -i -H "{'Accept-Language': 'en-US,en;q=0.5'}" 'https://manjaro-sway.download/weather/auto/?temperature_unit=celsius&wind_speed_unit=kmh'
HTTP/2 500 
date: Thu, 20 Feb 2025 12:39:19 GMT
content-length: 0
cf-placement: remote-FRA
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=HFemk4qmMSbKcFWhCkPkwSVlO2LBsHhlVTeLmRi7aYSg8fLAG%2BRuv26E3vPLNdzlRyPjoya76nH3yUYEK2RCu5aepeeRUPtVGN4B00%2BDkeAZyL%2FdhHGDHBpH2q4o%2BUdlB6jF3fOGze8%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 914e8f06cbfa0fab-EWR
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=96718&min_rtt=95927&rtt_var=28378&sent=6&recv=7&lost=0&retrans=0&sent_bytes=3390&recv_bytes=837&delivery_rate=29127&cwnd=141&unsent_bytes=0&cid=251a2d62e7a82f15&ts=270&x=0"
```
